import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1f2937',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 10,
    },
    skipButton: {
        padding: 10,
    },
    skipText: {
        color: '#9ca3af',
        fontSize: 16,
        fontWeight: '500',
    },
    scrollView: {
        flex: 1,
    },
    slideContainer: {
        // width:,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    contentContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        maxWidth: 350,
    },
    imageContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
    },
    iconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#3b82f6',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
    },
    iconText: {
        fontSize: 40,
    },
    illustrationContainer: {
        width: 280,
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderImage: {
        width: '100%',
        height: '100%',
        borderRadius: 20,
        backgroundColor: '#374151',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#4b5563',
        borderStyle: 'dashed',
    },
    placeholderText: {
        color: '#9ca3af',
        fontSize: 16,
        fontWeight: '500',
    },
    textContainer: {
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#ffffff',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 18,
        color: '#3b82f6',
        textAlign: 'center',
        marginBottom: 16,
        fontWeight: '600',
    },
    description: {
        fontSize: 16,
        color: '#d1d5db',
        textAlign: 'center',
        lineHeight: 24,
    },
    footer: {
        paddingHorizontal: 20,
        paddingBottom: 30,
        paddingTop: 20,
    },
    pagination: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
    },
    dot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginHorizontal: 6,
    },
    activeDot: {
        backgroundColor: '#3b82f6',
    },
    inactiveDot: {
        backgroundColor: '#4b5563',
    },
    nextButton: {
        backgroundColor: '#3b82f6',
        paddingVertical: 16,
        paddingHorizontal: 40,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#3b82f6',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    nextButtonText: {
        color: '#ffffff',
        fontSize: 18,
        fontWeight: '600',
    },
    // Illustration styles
    trackingIllustration: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#374151',
        borderRadius: 20,
        padding: 20,
    },
    busContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    bus: {
        width: 60,
        height: 40,
        backgroundColor: '#3b82f6',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    busText: {
        fontSize: 24,
    },
    trackingLine: {
        width: 60,
        height: 2,
        backgroundColor: '#3b82f6',
        marginHorizontal: 10,
    },
    locationPin: {
        width: 40,
        height: 40,
        backgroundColor: '#ef4444',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    pinText: {
        fontSize: 20,
    },
    mapBackground: {
        backgroundColor: '#1f2937',
        padding: 10,
        borderRadius: 8,
    },
    mapText: {
        color: '#3b82f6',
        fontSize: 14,
        fontWeight: '600',
    },
    stopsIllustration: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#374151',
        borderRadius: 20,
        padding: 20,
    },
    stopsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 20,
    },
    busStop: {
        width: 50,
        height: 50,
        backgroundColor: '#3b82f6',
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stopText: {
        fontSize: 24,
    },
    searchContainer: {
        backgroundColor: '#1f2937',
        padding: 12,
        borderRadius: 10,
    },
    searchText: {
        color: '#3b82f6',
        fontSize: 14,
        fontWeight: '600',
    },
    notificationIllustration: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#374151',
        borderRadius: 20,
        padding: 20,
    },
    phoneContainer: {
        marginBottom: 20,
    },
    phone: {
        width: 120,
        height: 200,
        backgroundColor: '#1f2937',
        borderRadius: 20,
        padding: 10,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    notification: {
        backgroundColor: '#3b82f6',
        padding: 10,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 20,
    },
    notifText: {
        fontSize: 16,
        marginRight: 8,
    },
    notifMessage: {
        color: '#ffffff',
        fontSize: 10,
        fontWeight: '500',
    },
    alertsContainer: {
        backgroundColor: '#1f2937',
        padding: 10,
        borderRadius: 8,
    },
    alertsText: {
        color: '#3b82f6',
        fontSize: 14,
        fontWeight: '600',
    },
});
export default styles;